# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from main import *
from PySide6 import QtCore, QtGui, QtWidgets
from PySide6.QtWidgets import QMainWindow
from qt_material import apply_stylesheet


class Ui_randxuehao(QMainWindow):

    def setupUi(self, randxuehao):
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("awa.ico"), QtGui.QIcon.Normal,
                       QtGui.QIcon.Off)
        randxuehao.setWindowIcon(icon)
        randxuehao.setObjectName("sc")
        randxuehao.resize(353, 133)
        self.sc = QtWidgets.QPushButton(randxuehao)
        self.sc.setGeometry(QtCore.QRect(230, 30, 93, 28))
        self.sc.setObjectName("chou")
        self.renshu = QtWidgets.QSpinBox(randxuehao)
        self.renshu.setGeometry(QtCore.QRect(20, 30, 201, 22))
        self.renshu.setMinimum(1)
        self.renshu.setMaximum(300)
        self.renshu.setObjectName("spinBox")
        self.about = QtWidgets.QPushButton(randxuehao)
        self.about.setGeometry(QtCore.QRect(250, 90, 93, 28))
        self.about.setObjectName("about")
        self.renshu.setSuffix(" 人")
        self.retranslateUi(randxuehao)
        self.renshu.setValue(40)
        QtCore.QMetaObject.connectSlotsByName(randxuehao)
        #self.sc.clicked.connect(onClickButton)
        self.about.clicked.connect(onAbout)
        self.sc.clicked.connect(self.renshum)
    def retranslateUi(self, randxuehao):
        _translate = QtCore.QCoreApplication.translate
        randxuehao.setWindowTitle(_translate("randxuehao", "随机抽学号"))
        self.sc.setText(_translate("randxuehao", "开始抽号"))
        self.about.setText(_translate("randxuehao", "关于"))

    def renshum(self, randxuehao):
        meb = self.renshu.value()
        get_num(meb)