# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from main import get_num
from main import onAbout
from PySide6 import QtCore, QtGui, QtWidgets
from PySide6.QtWidgets import QMainWindow

class Ui_randxuehao(object):
    def setupUi(self, randxuehao):
        randxuehao.setObjectName("randxuehao")
        randxuehao.resize(449, 191)
        self.sc = QtWidgets.QPushButton(randxuehao)
        self.sc.setGeometry(QtCore.QRect(320, 90, 93, 28))
        self.sc.setObjectName("sc")
        self.renshu = QtWidgets.QSpinBox(randxuehao)
        self.renshu.setGeometry(QtCore.QRect(110, 90, 201, 22))
        self.renshu.setMinimum(1)
        self.renshu.setMaximum(300)
        self.renshu.setObjectName("renshu")
        self.renshu.setValue(40)
        self.about = QtWidgets.QPushButton(randxuehao)
        self.about.setGeometry(QtCore.QRect(340, 150, 93, 28))
        self.about.setObjectName("about")
        self.tabWidget = QtWidgets.QTabWidget(randxuehao)
        self.tabWidget.setGeometry(QtCore.QRect(20, 10, 421, 71))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.comboBox = QtWidgets.QComboBox(self.tab)
        self.comboBox.setGeometry(QtCore.QRect(10, 10, 271, 21))
        self.comboBox.setObjectName("comboBox")

        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(310, 10, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.comboBox_2 = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_2.setGeometry(QtCore.QRect(20, 10, 87, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("一年级")
        self.comboBox_2.addItem("二年级")
        self.comboBox_2.addItem("三年级")
        self.comboBox_2.addItem("四年级")
        self.comboBox_2.addItem("五年级")
        self.comboBox_2.addItem("六年级")
        self.comboBox_2.addItem("七年级")
        self.comboBox_2.addItem("八年级")
        self.comboBox_2.addItem("九年级")
        self.comboBox_3 = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_3.setGeometry(QtCore.QRect(110, 10, 87, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("1班")
        self.comboBox_3.addItem("2班")
        self.comboBox_3.addItem("3班")
        self.comboBox_3.addItem("4班")
        self.comboBox_3.addItem("5班")
        self.comboBox_3.addItem("6班")
        self.comboBox_3.addItem("7班")
        self.comboBox_3.addItem("8班")
        self.save = QtWidgets.QPushButton(self.tab_2)
        self.save.setGeometry(QtCore.QRect(310, 10, 93, 28))
        self.save.setObjectName("save")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(randxuehao)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(randxuehao)
        #self.save.clicked.connect(onSave)
        self.about.clicked.connect(onAbout)
        self.sc.clicked.connect(self.renshum)

    def retranslateUi(self, randxuehao):
        _translate = QtCore.QCoreApplication.translate
        randxuehao.setWindowTitle(_translate("randxuehao", "随机抽学号"))
        self.sc.setText(_translate("randxuehao", "开抽"))
        self.about.setText(_translate("randxuehao", "关于"))
        self.pushButton.setText(_translate("randxuehao", "加载"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("randxuehao", "加载配置"))
        self.save.setText(_translate("randxuehao", "保存"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("randxuehao", "保存配置"))

    def renshum(self, randxuehao):
        meb = self.renshu.value()
        get_num(meb)